import type { Generator, GeneratorContext, GeneratorOutput, FabricSchema, EntitySchema, FieldSchema, RelationSchema } from '@newel/core'

const FIELD_TYPE_MAP: Record<string, string> = {
  string: 'string',
  number: 'number',
  integer: 'number',
  decimal: 'number',
  boolean: 'boolean',
  uuid: 'string',
  timestamp: 'Date',
  date: 'Date',
  email: 'string',
  url: 'string',
  json: 'unknown',
  enum: 'never', // overridden per-field
}

function fieldToTsType(field: FieldSchema): string {
  if (field.type === 'enum' && field.enumValues) {
    return field.enumValues.map(v => JSON.stringify(v)).join(' | ')
  }
  return FIELD_TYPE_MAP[field.type] ?? 'unknown'
}

function relationToTsType(rel: RelationSchema): string {
  switch (rel.kind) {
    case 'hasMany':
    case 'manyToMany':
      return `${rel.target}[]`
    case 'hasOne':
    case 'belongsTo':
      return rel.target
  }
}

function generateZodType(field: FieldSchema): string {
  if (field.type === 'enum' && field.enumValues) {
    const vals = field.enumValues.map(v => JSON.stringify(v)).join(', ')
    return `z.enum([${vals}])`
  }
  const base: Record<string, string> = {
    string: 'z.string()',
    number: 'z.number()',
    integer: 'z.number().int()',
    decimal: 'z.number()',
    boolean: 'z.boolean()',
    uuid: 'z.string().uuid()',
    timestamp: 'z.date()',
    date: 'z.date()',
    email: 'z.string().email()',
    url: 'z.string().url()',
    json: 'z.unknown()',
  }
  return base[field.type] ?? 'z.unknown()'
}

function generateEntityInterface(entity: EntitySchema): string {
  const lines: string[] = []

  // Collect ownerFields declared across behaviors for JSDoc
  const ownerFields = [...new Set(
    Object.values(entity.behaviors)
      .filter(b => b.auth?.ownerField)
      .map(b => b.auth!.ownerField!)
  )]

  if (ownerFields.length > 0) {
    lines.push(`/** @ownerField ${ownerFields.join(', ')} — ownership-based access control */`)
  }

  lines.push(`export interface ${entity.name} {`)
  for (const [, field] of Object.entries(entity.fields)) {
    const tsType = fieldToTsType(field)
    const optional = field.nullable ? '?' : ''
    lines.push(`  ${field.name}${optional}: ${tsType}`)
  }
  for (const [, rel] of Object.entries(entity.relations)) {
    const tsType = relationToTsType(rel)
    lines.push(`  ${rel.name}?: ${tsType}`)
  }
  lines.push('}')
  return lines.join('\n')
}

function generateZodSchema(entity: EntitySchema): string {
  const lines: string[] = []
  lines.push(`export const ${lcFirst(entity.name)}Schema = z.object({`)
  for (const [, field] of Object.entries(entity.fields)) {
    let zodType = generateZodType(field)
    if (field.nullable) zodType += '.nullable()'
    lines.push(`  ${field.name}: ${zodType},`)
  }
  lines.push('})')
  return lines.join('\n')
}

function generateStateEnum(entity: EntitySchema): string | null {
  const sm = entity.stateMachine
  if (!sm) return null
  const enumName = `${entity.name}State`
  const members = Object.keys(sm.states)
    .map(s => `  ${s.toUpperCase()} = '${s}',`)
    .join('\n')
  return `export enum ${enumName} {\n${members}\n}`
}

function lcFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1)
}

export class TypeScriptGenerator implements Generator {
  readonly name = 'typescript'
  readonly dependsOn: string[] = []

  async generate(schema: FabricSchema, _ctx: GeneratorContext): Promise<GeneratorOutput> {
    const sections: string[] = [
      `import { z } from 'zod'`,
      '',
    ]

    for (const entity of Object.values(schema.entities)) {
      const iface = generateEntityInterface(entity)
      const zod = generateZodSchema(entity)
      const stateEnum = generateStateEnum(entity)

      sections.push(`// #region ${entity.name}`)
      if (stateEnum) sections.push(stateEnum, '')
      sections.push(iface, '')
      sections.push(zod)
      sections.push(`// #endregion ${entity.name}`)
      sections.push('')
    }

    const content = sections.join('\n')

    return {
      files: [
        {
          path: 'typescript/index.ts',
          content,
          header: '// @generated by @newel/generator-typescript — do not edit\n',
        },
      ],
      artifacts: {
        entities: Object.keys(schema.entities),
      },
    }
  }
}
