import * as fs from 'fs'
import * as path from 'path'
import type { FabricSchema } from '../ir/types'
import type { Patch } from '../ir/patch'
import type { Generator, GeneratorOutput } from './types'
import type { IRSnapshot } from './snapshot'
import { topoSort } from './dag'
import { hashSchema, buildManifestEntries, writeManifest, type Manifest } from './manifest'
import { readSnapshot, writeSnapshot, buildSnapshot } from './snapshot'
import { applyPatches, collectSuppressPatterns, isSuppressed } from '../ir/apply-patches'

export interface RunnerOptions {
  outputDir: string
  dryRun?: boolean
  /** Semantic patches applied to the resolved IR before generators run. */
  patches?: Patch[]
}

export interface RunResult {
  manifest: Manifest
  outputs: Map<string, GeneratorOutput>
  snapshot: IRSnapshot
  previousSnapshot: IRSnapshot | null
  /** File paths suppressed by patches (relative to outputDir). */
  suppressedFiles: string[]
}

export async function runGenerators(
  schema: FabricSchema,
  generators: Generator[],
  options: RunnerOptions,
): Promise<RunResult> {
  const sorted = topoSort(generators)
  const outputs = new Map<string, GeneratorOutput>()
  const allEntries: Manifest['files'] = []
  const generatedAt = new Date().toISOString()

  const patches = options.patches ?? []
  const patchedSchema = applyPatches(schema, patches)
  const suppressPatterns = collectSuppressPatterns(patches)

  // Snapshot and manifest hash are both based on the patched schema so that
  // check-drift compares against the patched IR, not the raw IR.
  const schemaHash = hashSchema(patchedSchema)

  const previousSnapshot = readSnapshot(options.outputDir)
  const snapshot = buildSnapshot(patchedSchema, generatedAt)

  const suppressedFiles: string[] = []

  for (const gen of sorted) {
    const ctx = {
      outputDir: path.join(options.outputDir, gen.name),
      outputs,
      previousSnapshot: previousSnapshot ?? undefined,
    }

    const output = await gen.generate(patchedSchema, ctx)

    // Filter suppressed files before writing or adding to manifest.
    const kept: typeof output.files = []
    for (const file of output.files) {
      if (isSuppressed(file.path, suppressPatterns)) {
        suppressedFiles.push(file.path)
      } else {
        kept.push(file)
      }
    }
    const filteredOutput: GeneratorOutput = { ...output, files: kept }
    outputs.set(gen.name, filteredOutput)

    if (!options.dryRun) {
      for (const file of kept) {
        const filePath = path.join(options.outputDir, file.path)
        const dir = path.dirname(filePath)
        fs.mkdirSync(dir, { recursive: true })
        const header = file.header ?? `// @generated by quoin — do not edit\n`
        fs.writeFileSync(filePath, header + file.content)
      }
    }

    allEntries.push(...buildManifestEntries(gen.name, filteredOutput, schemaHash))
  }

  const manifest: Manifest = {
    generatedAt,
    schemaHash,
    files: allEntries,
  }

  if (!options.dryRun) {
    writeManifest(options.outputDir, manifest)
    writeSnapshot(options.outputDir, snapshot)
  }

  return { manifest, outputs, snapshot, previousSnapshot, suppressedFiles }
}
