import * as fs from 'fs'
import * as path from 'path'
import type { FabricSchema } from '../ir/types'
import type { Generator, GeneratorOutput } from './types'
import { topoSort } from './dag'
import { hashSchema, buildManifestEntries, writeManifest, type Manifest } from './manifest'

export interface RunnerOptions {
  outputDir: string
  dryRun?: boolean
}

export interface RunResult {
  manifest: Manifest
  outputs: Map<string, GeneratorOutput>
}

export async function runGenerators(
  schema: FabricSchema,
  generators: Generator[],
  options: RunnerOptions,
): Promise<RunResult> {
  const sorted = topoSort(generators)
  const outputs = new Map<string, GeneratorOutput>()
  const schemaHash = hashSchema(schema)
  const allEntries: Manifest['files'] = []

  for (const gen of sorted) {
    const ctx = {
      outputDir: path.join(options.outputDir, gen.name),
      outputs,
    }

    const output = await gen.generate(schema, ctx)
    outputs.set(gen.name, output)

    if (!options.dryRun) {
      for (const file of output.files) {
        const filePath = path.join(options.outputDir, file.path)
        const dir = path.dirname(filePath)
        fs.mkdirSync(dir, { recursive: true })
        const header = file.header ?? `// @generated by quoin — do not edit\n`
        fs.writeFileSync(filePath, header + file.content)
      }
    }

    allEntries.push(...buildManifestEntries(gen.name, output, schemaHash))
  }

  const manifest: Manifest = {
    generatedAt: new Date().toISOString(),
    schemaHash,
    files: allEntries,
  }

  if (!options.dryRun) {
    writeManifest(options.outputDir, manifest)
  }

  return { manifest, outputs }
}
