import * as os from 'os'
import * as fs from 'fs'
import * as path from 'path'
import { runGenerators } from './runner'
import type { Generator, GeneratorContext, GeneratorOutput } from './types'
import type { FabricSchema } from '../ir/types'

const minimalSchema: FabricSchema = {
  version: '1.0.0',
  meta: { name: 'test' },
  entities: {},
  apis: {},
}

function makeStubGen(name: string, dependsOn: string[] = []): Generator {
  return {
    name,
    dependsOn,
    async generate(_schema: FabricSchema, _ctx: GeneratorContext): Promise<GeneratorOutput> {
      return {
        files: [{ path: `${name}/output.txt`, content: `generated by ${name}` }],
        artifacts: { [name]: true },
      }
    },
  }
}

describe('runGenerators', () => {
  let tmpDir: string

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'quoin-test-'))
  })

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('writes generated files to disk', async () => {
    const gen = makeStubGen('stub')
    await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })
    const filePath = path.join(tmpDir, 'stub/output.txt')
    expect(fs.existsSync(filePath)).toBe(true)
    expect(fs.readFileSync(filePath, 'utf-8')).toContain('generated by stub')
  })

  it('writes manifest', async () => {
    const gen = makeStubGen('stub')
    const result = await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })
    expect(result.manifest.files).toHaveLength(1)
    expect(result.manifest.files[0].generator).toBe('stub')
    const manifestPath = path.join(tmpDir, 'quoin.manifest.json')
    expect(fs.existsSync(manifestPath)).toBe(true)
  })

  it('threads outputs between generators', async () => {
    let upstreamSeen = false
    const upstream = makeStubGen('upstream')
    const downstream: Generator = {
      name: 'downstream',
      dependsOn: ['upstream'],
      async generate(_s, ctx) {
        upstreamSeen = ctx.outputs.has('upstream')
        return { files: [] }
      },
    }
    await runGenerators(minimalSchema, [downstream, upstream], { outputDir: tmpDir })
    expect(upstreamSeen).toBe(true)
  })

  it('dryRun does not write files', async () => {
    const gen = makeStubGen('stub')
    await runGenerators(minimalSchema, [gen], { outputDir: tmpDir, dryRun: true })
    expect(fs.existsSync(path.join(tmpDir, 'stub/output.txt'))).toBe(false)
  })
})
