import type {
  Generator,
  GeneratorContext,
  GeneratorOutput,
  FabricSchema,
  EntitySchema,
  FieldSchema,
  RelationSchema,
} from '@quoin/core'

// --- SQL type mapping ---

function fieldToSqlType(field: FieldSchema): string {
  if (field.type === 'enum' && field.enumValues) {
    const vals = field.enumValues.map(v => `'${v}'`).join(', ')
    return `VARCHAR(64) CHECK (${field.name} IN (${vals}))`
  }
  const map: Record<string, string> = {
    string:    'TEXT',
    number:    'NUMERIC',
    integer:   'INTEGER',
    decimal:   'NUMERIC(19, 4)',
    boolean:   'BOOLEAN',
    uuid:      'UUID',
    timestamp: 'TIMESTAMPTZ',
    date:      'DATE',
    email:     'TEXT',
    url:       'TEXT',
    json:      'JSONB',
  }
  return map[field.type] ?? 'TEXT'
}

function toSnakeCase(s: string): string {
  return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '')
}

function tableName(entityName: string): string {
  return toSnakeCase(entityName) + 's'
}

// --- Column DDL ---

function renderColumn(field: FieldSchema): string {
  const colName = toSnakeCase(field.name)
  const sqlType = fieldToSqlType(field)
  const parts: string[] = [`  ${colName} ${sqlType}`]

  if (field.primaryKey) parts.push('PRIMARY KEY')
  if (!field.nullable && !field.primaryKey) parts.push('NOT NULL')

  return parts.join(' ')
}

// --- FK constraints ---

function renderFkConstraint(
  entityName: string,
  field: FieldSchema,
): string | null {
  if (!field.foreignKey) return null
  const [refEntity, refField = 'id'] = field.foreignKey.split('.')
  const colName = toSnakeCase(field.name)
  const constraintName = `fk_${toSnakeCase(entityName)}_${colName}`
  return `  CONSTRAINT ${constraintName} FOREIGN KEY (${colName}) REFERENCES ${tableName(refEntity)} (${toSnakeCase(refField)})`
}

// --- Join table for manyToMany ---

function renderJoinTable(rel: RelationSchema, ownerEntityName: string): string | null {
  if (rel.kind !== 'manyToMany') return null

  const left = toSnakeCase(ownerEntityName)
  const right = toSnakeCase(rel.target)
  const joinTable = rel.through ? toSnakeCase(rel.through) : `${left}_${right}`

  return [
    `CREATE TABLE IF NOT EXISTS ${joinTable} (`,
    `  ${left}_id UUID NOT NULL,`,
    `  ${right}_id UUID NOT NULL,`,
    `  PRIMARY KEY (${left}_id, ${right}_id),`,
    `  CONSTRAINT fk_${joinTable}_${left} FOREIGN KEY (${left}_id) REFERENCES ${tableName(ownerEntityName)} (id),`,
    `  CONSTRAINT fk_${joinTable}_${right} FOREIGN KEY (${right}_id) REFERENCES ${tableName(rel.target)} (id)`,
    ');',
  ].join('\n')
}

// --- CREATE TABLE ---

function renderCreateTable(entityName: string, entity: EntitySchema): string {
  const table = tableName(entityName)
  const lines: string[] = [`CREATE TABLE IF NOT EXISTS ${table} (`]
  const cols: string[] = []
  const constraints: string[] = []

  for (const field of Object.values(entity.fields)) {
    cols.push(renderColumn(field))
    const fk = renderFkConstraint(entityName, field)
    if (fk) constraints.push(fk)
  }

  const allLines = [...cols, ...constraints]
  for (let i = 0; i < allLines.length; i++) {
    lines.push(allLines[i] + (i < allLines.length - 1 ? ',' : ''))
  }

  lines.push(');')
  return lines.join('\n')
}

// --- Full DDL file ---

function generateDdl(schema: FabricSchema): string {
  const blocks: string[] = [
    `-- Generated from ${schema.meta.name} v${schema.meta.version ?? '1.0.0'}`,
    '',
  ]

  // Tables in stable order
  for (const [name, entity] of Object.entries(schema.entities)) {
    blocks.push(renderCreateTable(name, entity))
    blocks.push('')
  }

  // Join tables for manyToMany relations
  for (const [entityName, entity] of Object.entries(schema.entities)) {
    for (const rel of Object.values(entity.relations)) {
      const joinTable = renderJoinTable(rel, entityName)
      if (joinTable) {
        blocks.push(joinTable)
        blocks.push('')
      }
    }
  }

  return blocks.join('\n')
}

// --- Migration file ---

function generateMigration(schema: FabricSchema, version: string): string {
  const lines: string[] = [
    `-- Migration: initial schema for ${schema.meta.name}`,
    `-- Version: ${version}`,
    '',
    '-- Up',
    generateDdl(schema),
  ]
  return lines.join('\n')
}

export class SqlGenerator implements Generator {
  readonly name = 'sql'
  readonly dependsOn: string[] = []

  async generate(schema: FabricSchema, _ctx: GeneratorContext): Promise<GeneratorOutput> {
    const version = schema.meta.version ?? '1.0.0'
    const migrationSlug = version.replace(/\./g, '_')

    return {
      files: [
        {
          path: 'sql/schema.sql',
          content: generateDdl(schema),
          header: `-- @generated by @quoin/generator-sql — do not edit\n`,
        },
        {
          path: `sql/migrations/${migrationSlug}__initial.sql`,
          content: generateMigration(schema, version),
          header: `-- @generated by @quoin/generator-sql — do not edit\n`,
        },
      ],
    }
  }
}
